# tattoo_frontend/analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    unused_import: error
    invalid_annotation_target: info

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_locals
    - use_key_in_widget_constructors
    - avoid_print
    - unnecessary_late
    - prefer_single_quotes
