# melos.yaml
name: tattoo_frontend
packages:
  - apps/**
  - packages/core_domain
  - packages/core_interfaces
  - packages/core_utils
  - packages/design
  - packages/features
  - packages/language
  - packages/network
  - packages/observability
  - packages/storage_hive

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: |
      dart run melos exec -c 4 -- \
        sh -lc 'flutter analyze . --no-fatal-warnings || dart analyze .'

  l10n:
    run: |
      dart run melos exec --scope=language -- \
        flutter gen-l10n

  test:
    run: |
      dart run melos run l10n || true
      dart run melos exec -c 2 --dir-exists=test -- \
        sh -lc 'flutter test --coverage || dart test --coverage=coverage'