arb-dir: lib/l10n
output-dir: lib/src/l10n
template-arb-file: app_en.arb
output-localization-file: app_lang.dart
output-class: AppLang
nullable-getter: false
untranslated-messages-file: l10n_untranslated.json